name: Create User Portfolio

on:
  repository_dispatch:
    types: [create_profile]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create User Profile
        run: |
          USERNAME="${{ github.event.client_payload.name }}"
          BIO="${{ github.event.client_payload.bio }}"
          
          # Create user profile directory
          mkdir -p "profiles/$USERNAME"
          
          # Generate index.html with user details
          echo "<h1>Welcome $USERNAME</h1>" > profiles/$USERNAME/index.html
          echo "<p>Bio: $BIO</p>" >> profiles/$USERNAME/index.html
          
          # Commit and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add profiles/$USERNAME/index.html
          git commit -m "Created profile for $USERNAME"
          git push

      - name: Done
        run: echo "Portfolio page created for ${{ github.event.client_payload.name }}"
